apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
      - image: us.icr.io/sn-labs-sathvikmalle/dealership:latest # <-- REPLACE 'your-name-space' HERE
        imagePullPolicy: Always
        name: dealership
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always

--- # This is a YAML document separator

apiVersion: v1
kind: Service
metadata:
  labels:
    run: dealership
  name: dealership
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: dealership
  type: ClusterIP # Use ClusterIP for internal service access, or NodePort/LoadBalancer for external access
